In [185]:
import numpy as np
from IPython.display import display

CSS = """
.output {
    flex-direction: column;
}
"""

In [186]:
accordion.set_title(0, 'Раздел 1')

1. Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$

##### Решение

In [187]:
A = np.array([[1, 2, 0],
              [0, 0, 5],
              [3, -4, 2],
              [1, 6, 5],
              [0, 1, 0]])

In [188]:
U, s, W = np.linalg.svd(A)

In [189]:
U

array([[ 0.171,  0.157, -0.531, -0.799, -0.162],
       [ 0.393, -0.529,  0.613, -0.434,  0.031],
       [-0.144, -0.824, -0.524,  0.14 ,  0.074],
       [ 0.888,  0.061, -0.247,  0.378, -0.06 ],
       [ 0.081,  0.108, -0.082, -0.105,  0.982]])

In [190]:
# Транспонируем матрицу W
V = W.T
V

array([[ 0.071, -0.367, -0.927],
       [ 0.717,  0.665, -0.208],
       [ 0.693, -0.65 ,  0.311]])

In [191]:
# s - список диагональных элементов, его нужно привести к виду диагональной матрицы для наглядности
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s
D

array([[8.825, 0.   , 0.   ],
       [0.   , 6.141, 0.   ],
       [0.   , 0.   , 2.533],
       [0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   ]])

In [192]:
display(U,D,V)

array([[ 0.171,  0.157, -0.531, -0.799, -0.162],
       [ 0.393, -0.529,  0.613, -0.434,  0.031],
       [-0.144, -0.824, -0.524,  0.14 ,  0.074],
       [ 0.888,  0.061, -0.247,  0.378, -0.06 ],
       [ 0.081,  0.108, -0.082, -0.105,  0.982]])

array([[8.825, 0.   , 0.   ],
       [0.   , 6.141, 0.   ],
       [0.   , 0.   , 2.533],
       [0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   ]])

array([[ 0.071, -0.367, -0.927],
       [ 0.717,  0.665, -0.208],
       [ 0.693, -0.65 ,  0.311]])

In [193]:
# Проведем проверку
print(np.dot(np.dot(U, D), V.T))

[[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1.  0.]]


2. Для матрицы из предыдущего задания найти:

    а) евклидову норму;
    
    б) норму Фробениуса.

##### Решение

In [194]:
max_S = 0
for i in range(len(S)):
    if S[i] > max_S:
        max_S = S[i]
print(f'Евклидова норма матрицы А равна максимальному сингулярному числу {max_S}')

Евклидова норма матрицы А равна максимальному сингулярному числу 8.824868854820442


In [195]:
F = 0
for i in range(len(S)):
    F += S[i]*S[i]
F = np.sqrt(F)
print(f'Норма Фробениуса матрицы А равна корню из суммы квадратов сингулярных чисел {F}')

Норма Фробениуса матрицы А равна корню из суммы квадратов сингулярных чисел 11.045361017187261
