# Линейная алгебра
## Домашнее задание к первому уроку "Линейное пространство. Основные понятия. Часть 1"


In [4]:
from scipy.linalg import solve
import numpy as np
from numpy.linalg import norm

### Часть 1

__1.__ Исследовать на линейную зависимость:
$$f_{1}(x)=e^{x}, f_{2}(x)=1, f_{3}(x)=x+1, f_{4}(x)=x-e^{x}.$$

#### Решение:

Можно заметить что 
$$f_1(x) = -f_4(x) - f_3(x) + f_2(x)$$
А раз $f_1$ можно выразить через $f_2$, $f_3$ и $f_4$, значит они линейно зависимы

__2.__ Исследовать на линейную зависимость:
$$f_{1}(x)=2, f_{2}(x)=x, f_{3}(x)=x^{2}, f_{4}(x)=(x+1)^{2}.$$
#### Решение:
$$f_4(x) = (x+1)^2 = x^2 + 2x + 1 = f_{3}(x) + 2f_{2}(x) + \frac{f_{1}(x)}{2}$$
Значит $f_1$, $f_2$, $f_3$ и $f_4$ линейно зависимы

__3.__ Найти координаты вектора $x = (2, 3, 5)\in \mathbb{R}^{3}$ в базисе $b_{1}=(0, 0, 10)$, $b_{2}=(2, 0, 0)$, $b_{3}=(0, 1, 0)$.

#### Решение: 
решение очевидно, но все же запишем в матричном виде и решим используя метод `solve` пакета `scipy.linalg`

In [10]:
B = np.array([
    [0, 0, 10],
    [2, 0, 0],
    [0, 1, 0]]).T

X = np.array([2,3,5])

X_new = solve(B, X)

X_new

array([0.5, 1. , 3. ])

__4.__ Найти координаты вектора $3x^{2}-2x+2\in\mathbb{R}^{3}[x]$:

   а) в базисе $1$, $x$, $x^{2}$;

   б) в базисе $x^{2}$, $x-1$, $1$.

#### Решение:
Также, запишем базисы в матричном виде и решим

In [13]:
X = np.array([3, -2, 2])
B_a = np.array([
    [0,0,1],
    [0,1,0],
    [1,0,0]
]).T

B_b = np.array([
    [1,0,0],
    [0,1,-1],
    [0,0,1]
])


print(f'{solve(B_a, X)}, \n{solve(B_b, X)}')

[ 2. -2.  3.], 
[3. 0. 2.]


__5.__ Установить, является ли линейным подпространством:

а) совокупность всех векторов трехмерного пространства, у которых по крайней мере одна из первых двух координат равна нулю;
    
б) все векторы, являющиеся линейными комбинациями данных векторов $\{u_{1}, u_{2}, ..., u_{n}\}$.


Решение:

а) Т.е. требуется исследовать систему векторов такую, что координатами любых $a$ и $b$ из этой системы могут быть следующие варианты: $$1. a = (0, \alpha, \beta), b = (0, \gamma, \delta)$$ $$2. a = (0, 0, \beta), b = (0, \gamma, \delta)$$ $$3. a = (0, \alpha, \beta), b = (0, 0, \delta)$$ $$4. a = (0, 0, \beta), b = (0, 0, \delta)$$ $$5. a = (\alpha, 0, \beta), b = (0, \gamma, \delta)$$ $$6. a = (0, \alpha, \beta), b = (\gamma, 0, \delta)$$

Проверим эти варианты на операции сложения и умножения на скаляр: $$ 1. a+b = (0, \alpha+\gamma, \beta+\delta), k\cdot a =  (0, k\alpha, k\beta),$$ аналогично var. 2, 3, 4, но в var.5, 6: $$ 5. a+b = (\alpha, \gamma, \beta+\delta),  k\cdot a =  (k\alpha, 0, k\beta),$$ т.е. результат сложения векторов не всегда будет принадлежать этому подпространству => совокупность всех векторов трехмерного пространства, у которых по крайней мере одна из первых двух координат равна нулю не является линейным подпространством.

б) по отношению ко всем векторам, являющимся линейными комбинациями данных векторов $\{u_{1}, u_{2}, ..., u_{n}\}$ будут существовать варианты, аналогичные var.5, 6 из пп.а), т.е. они также не являются линейным подпространством.

### Часть 2

__1.__ Найти скалярное произведение векторов $x, y \in \mathbb{R}$:<br>
а) $x=(0,-3, 6),~y=(-4, 7, 9);$<br>
б) $x=(7, -4, 0, 1),~y=(-3, 1, 11, 2).$

#### Решение:

a)

In [14]:
x = np.array([0, -3, 6])
y = np.array([-4, 7, 9])

np.dot(x,y)

33

б)

In [15]:
x = np.array([7, -4, 0, 1])
y = np.array([-3, 1, 11, 2])

np.dot(x,y)

-23

__2.__ Найти нормы векторов $(4, 2, 4)$ и $(12, 3, 4)$ и угол между ними.
#### Решение:


In [17]:
a = np.array([4, 2, 4])
b = np.array([12, 3, 4])

a_norm = np.linalg.norm(a)
b_norm = np.linalg.norm(b)

cos_phi = np.dot(a, b) / a_norm / b_norm

print(f'нормы векторов: \na: {a_norm} \nb: {b_norm}')
print(f'Угол между векторами: {np.arccos(cos_phi)}')

нормы векторов: 
a: 6.0 
b: 13.0
Угол между векторами: 0.4568740035326613


__3.__ Будет ли линейное пространство евклидовым, если за скалярное произведение принять:<br>
а) произведение длин векторов;

б) утроенное обычное скалярное произведение векторов?
 
 
   
  Решение:
                                  
  Нет, потому что скалярное произведение векторов равно произведению длин векторов на косинус угла между ними, а косинус принимает значения от -1 до 1. Следовательно, скалярное произведение векторов меньше или равно произведению их длин.

  
Скалярное произведение евклидова пространства должно подчиняться четырем аксиомам:
1) $(x,y)=(y,x);$
2) $(\lambda x, y)=\lambda(x, y);$
3) $(x_{1}+x_{2},y)=(x_{1},y)+(x_{2},y);$
4) $(x, x)\geq0$, причем $(x,x)=0\Leftrightarrow x=0.$
Заметим, что из 3 аксиомы следует:
$\left|x_{1}\right|cos\alpha_{1}+\left|x_{2}\right|cos\alpha_{2}=\left|x_{1}+x_{2}\right|cos\alpha$

а) Проверим, выполняются ли эти аксиомы, если $(x, y) = \left|x\right|\cdot\left|y\right| $

1) $\left|x\right|\cdot\left|y\right| = \left|y\right|\cdot\left|x\right|$ - выполняется
2) $(\lambda \cdot \left|x\right|)\cdot\left|y\right|= \lambda \cdot (\left|x\right|\cdot\left|y\right|)$ - выполняется
3) $\left|x_{1}\right|\cdot\left|y\right| + \left|x_{2}\right|\cdot\left|y\right|= (\left|x_{1}\right|+\left|x_{2}\right|)\cdot\left|y\right|$,
но $\left|x_{1}\right| + \left|x_{2}\right| \geq \left|x_{1}+x_{2}\right|$, так как $(\sqrt{\sum_{i}|x_{1i}|^{2}}+\sqrt{\sum_{i}|x_{2i}|^{2}}) \geq \sqrt{\sum_{i}|x_{1i}+x_{2i}|^{2}}|$ =>
$(x_{1}+x_{2},y)\leq(x_{1},y)+(x_{2},y)$, то есть 3 аксиома не выполняется
4) $(x, x)\geq0$, причем $(x,x)=0\Leftrightarrow x=0$ - выполняется
Так как 3 аксиома не выполняется => если за скалярное произведение принять произведение длин векторов, то линейное пространство не будет евклидовым.

б) Проверим, выполняются ли эти аксиомы, если $(x, y) = 3 \cdot \left|x\right|\cdot\left|y\right|cos\alpha.$

1) $(x,y)=(y,x)$ - выполняется
2) $(\lambda x, y)=\lambda(x, y)$ - выполняется
3) $(x_{1},y)+(x_{2},y)=3 \cdot \left|x_{1}\right|\cdot\left|y\right|cos\alpha_{1} +3 \cdot \left|x_{2}\right|\cdot\left|y\right|cos\alpha_{2}=3(\left|x_{1}\right|cos\alpha_{1}+\left|x_{2}\right|cos\alpha_{2})\left|y\right|= 3\cdot(\left|x_{1}+x_{2}\right|cos\alpha)\left|y\right|= (x_{1}+x_{2},y) $ - выполняется
4) $(x, x)\geq0$, причем $(x,x)=0\Leftrightarrow x=0$ - выполняется
Аксиомы выполняются => если за скалярное произведение принять утроенное обычное скалярное произведение векторов, то линейное пространство будет евклидовым.

__4.__ Какие из нижеперечисленных векторов образуют ортонормированный базис в линейном пространстве $\mathbb{R}^{3}$:<br>
а) $(1,0,0),(0,0,1);$ <br>

б) $(1/\sqrt{2},-1/\sqrt{2},0),(1/\sqrt{2},1/\sqrt{2},0), (0,0,1);$<br>

Решение:

а) $(1,0,0),(0,0,1)$ в 3-мерном линейном пространстве $\mathbb{R}^{3}$ базисом не являются, т.к. базис должен содержать 3 вектора.

б) $(1/\sqrt{2},-1/\sqrt{2},0),(1/\sqrt{2},1/\sqrt{2},0), (0,0,1)$ в 3-мерном линейном пространстве $\mathbb{R}^{3}$ являются ортонормированным базисом, т.к.:

In [6]:
e_1 = np.array([1/np.sqrt(2), -1/np.sqrt(2), 0])  
e_2 = np.array([1/np.sqrt(2), 1/np.sqrt(2), 0])
e_3 = np.array([0, 0, 1])
norm(e_1), norm(e_2), norm(e_3)

(0.9999999999999999, 0.9999999999999999, 1.0)

In [7]:
e_1.dot(e_2), e_1.dot(e_3), e_2.dot(e_3)


(0.0, 0.0, 0.0)

в) $(1/2, -1/2, 0), (0, 1/2, 1/2), (0,0,1)$ в 3-мерном линейном пространстве $\mathbb{R}^{3}$ не являются ортонормированным базисом, т.к.:

In [8]:
e_1 = np.array([1/2, -1/2, 0])  
e_2 = np.array([0, 1/2, 1/2])
e_3 = np.array([0, 0, 1])
norm(e_1), norm(e_2), norm(e_3)

(0.7071067811865476, 0.7071067811865476, 1.0)

In [9]:
e_1.dot(e_2), e_1.dot(e_3), e_2.dot(e_3)

(-0.25, 0.0, 0.5)

г) $(1,0,0),(0,1,0),(0,0,1)$ в 3-мерном линейном пространстве $\mathbb{R}^{3}$ являются ортонормированным базисом, т.к.:

In [10]:
e_1 = np.array([1, 0, 0])  
e_2 = np.array([0, 1, 0])
e_3 = np.array([0, 0, 1])
norm(e_1), norm(e_2), norm(e_3)

(1.0, 1.0, 1.0)

In [11]:
e_1.dot(e_2), e_1.dot(e_3), e_2.dot(e_3)

(0, 0, 0)